# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QgisSkjalftalisa
                                 A QGIS plugin
 Interface for Veðurstofan earthquake data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-19
        copyright            : (C) 2024 by William M. Moreland
        email                : william@moreland.is
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QgisSkjalftalisa class from file QgisSkjalftalisa.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qgis_skjalfalisa import QgisSkjalftalisa
    return QgisSkjalftalisa(iface)
